### ISSUE TITLE
Don't enforce hiredis installation. Just recommend it.

### ISSUE THREAD

**Issue by Ghnuberath** [raveljs/ravel#126]
It's probably too opinionated to require it.

**Comment by mlaccetti** [comment]
What happens if it isn't installed?  Session clustering no happy out of box?  Or does session clustering move to another module with a default Redis-backed option?

**Comment by Ghnuberath** [comment]
node-redis just falls back to a pure js redis implementation. Hiredis is the optional, accelerated, native peer package.

**Comment by mlaccetti** [comment]
Ah, that's perfectly fine.  Less `node-gyp`, better.
