### ISSUE TITLE
Ravel.module(s), Ravel.routes and Ravel.resource(s) should support absolute paths

### ISSUE THREAD

**Issue by mlaccetti** [raveljs/ravel#167]
In `modules.js`, existence of a module is done via a local check (`!fs.lstatSync(basePath).isDirectory()`), but in `module.js`, it is loaded via an absolute path (`require(upath.join(this.cwd, modulePath))`).

I am having a party in my tests where the local path won't resolve, so I register the modules directory via an absolute path (`app.modules(__dirname + '/modules');`), which then blows up.

**Comment by mlaccetti** [comment]
I'll take this for a spin and let you know.  I think it might be better to go the other way - let the user choose the local or absolute path and check it that way.  Could also be the way I'm writing a test, though - will find out shortly!

**Comment by mlaccetti** [comment]
Nope, still not a happy camper - the `cwd` is relative to the process, which means that it looks for `project/modules` instead of `project/src/modules`.  This is probably some weirdness related to Mocha, ES6, and TypeScript transpilation.  Might need to flatten the directories somehow, so that the contents of `src` and `test` are both dumped to a `dist`, and the tests run from there.  Though, the `require('../../src/app.js')` would break, so I'm at a bit of a loss as to the correct approach.

Aside from letting the user specify an absolute path when loading modules; if they have a relative path, do a `join`; if an absolute path, just proceed without the join.

**Comment by Ghnuberath** [comment]
What's your project layout right now? Generally, I'd probably have:

```
src/
  app.js
test/
dist/
  src/
    app.js
  test/
```

`dist/` would  be the cwd for the test, preserving relative requires.

You're definitely right about detecting and handling absolute paths though. Will push a fix for that to this branch in a sec.

**Comment by Ghnuberath** [comment]
Fixed by #168
