### ISSUE TITLE
Allow .ravelrc to reference environment variables

### ISSUE THREAD

**Issue by mlaccetti** [raveljs/ravel#207]
If including something like:
```
{
  "github client id": "YOUR_CLIENT_ID",
  "github client secret" : "YOUR_CLIENT_SECRET"
}
```

It'd, be nice if we could use `$GITHUB_CLIENT_ID` and have it be noticed/injected.

**Comment by kevinjqiu** [comment]
@Ghnuberath I guess this can be closed now?

**Comment by Ghnuberath** [comment]
Sorry @kevinjqiu, habit. In the future, include the string `"Fixes #issno"` in your PR description and the issue will auto-close when I merge. https://help.github.com/articles/closing-issues-using-keywords/

**Comment by kevinjqiu** [comment]
Yeah I forgot.  I do use that keyword for other PRs :)
