### ISSUE TITLE
Syntatic sugar for parameterized middleware (middleware factories)

### ISSUE THREAD

**Issue by Ghnuberath** [raveljs/ravel#253]
`@before` does not support passing parameters to middleware factories - the function injected must literally be the middleware itself.

It would be very useful to have API-level support for writing and using "configurable" middleware: functions which take parameters and return middleware.

**Comment by Ghnuberath** [comment]
I'd be curious to hear your idea. Let's discuss.

**Comment by adamocarolli** [comment]
@Ghnuberath we had this discussion some time ago and settled on something like:

`@before('middleware1', {'middleware2': {'arg1': true, 'arg2': 'aValue'}}, 'middleware3')`

I'm curious on your thoughts of allowing users to create custom middleware decorators. ie.


`@middleware1`
`@middleware2(arg1, arg2, ...)`
`@middleware3`

**Comment by Ghnuberath** [comment]
Things I don't like about that:

- The decorator spec is in flux, so we'd be encouraging people to write things they'd have to rewrite later. Currently that flux is hidden behind Ravel-supplied decorators, which we'll update when the spec is finalized in a way that is invisible to apps.
- We could try to conceal the flux behind a factory method that returned a decorator, but even the parameters it would take would likely have to change in the future, so I don't think this solves the problem
- This pattern isn't compatible with dependency injection. You'd have to manually import them by hand, which runs contrary to the DI-focus of Ravel. Each `Routes` or `Resource` class would have a large number of `require`s in addition to `@inject`s, mixing patterns.
