### ISSUE TITLE
Redis failures at startup fail the app

### ISSUE THREAD

**Issue by mlaccetti** [raveljs/ravel#275]
In the [kvstore](https://github.com/raveljs/ravel/blob/master/lib/util/kvstore.js#L78), there is the following:
```
client.on('error', ravelInstance.$log.error);
```

If my Redis is mis-configured (i.e. the Docker container isn't setup properly), the client will throw an error, but the logger isn't actually properly configured, and we'll get the following boom:
```
C:\Users\mlacc\workspace\twitist\node_modules\ravel\dist\util\log.js:75
  error() {return this[sLogger].error.apply(this[sLogger], arguments);}
                                ^

TypeError: Cannot read property 'error' of undefined
    at RedisClient.error (C:\Users\mlacc\workspace\twitist\node_modules\ravel\dist\util\log.js:75:33)
```

If I switch the `ravelInstance.$log.error` to `console.error` just to validate it, I'll get the actual Redis error.

**Comment by Ghnuberath** [comment]
Good catch!
