### ISSUE TITLE
Create a Yeoman generator

### ISSUE THREAD

**Issue by LLay** [raveljs/ravel#47]

**Comment by LLay** [comment]
Unsure of proper directory structure. See http://yeoman.io/authoring/ for more info

**Comment by mlaccetti** [comment]
```
├───package.json
└───generators/
    ├───app/
    │   └───index.js
    └───router/
        └───index.js
```

We only really need 'app' (the default) for now, and then add the additional generators (for modules, routes, etc.) as required.

**Comment by Ghnuberath** [comment]
This issue should be logged against a new project raveljs/ravel-yeoman-generator.
