### ISSUE TITLE
Add default properties file for bootstrapping

### ISSUE THREAD

**Issue by mlaccetti** [raveljs/ravel#6]
Add some default 'ravel.properties' that can be overridden by command-line/environment variables to load default DB/redis/oauth/... information.

**Comment by Ghnuberath** [comment]
The plan is to implement this as a separate project, in the form of a yeoman generator complete with:
 - a directory structure
 - default modules (ravel-google-oauth2-provider, ravel-mysql-provider)
 - default properties
 - a dev Vagrant vm (redis + mysql)
 - a build file (grunt/gulp) which helps bootstrap both development and test suite creation

**Comment by mlaccetti** [comment]
Aside from *eww yeoman*, sure.  :)
